/* eslint-disable @next/next/no-img-element */
import { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";
import { MDXRemote, MDXRemoteSerializeResult } from "next-mdx-remote";
import Head from "next/head";
import Image from "next/image";
import qs from "qs";
import React from "react";
import { fetchArticlBySlug } from "../../http";
import { IArticle, ICollectionResponse } from "../../types";
import { dateFormat, serializedMarkDown } from "../../utils";

interface IPropType {
  article: IArticle;
  notFound?: boolean;
}

const Slug = ({ article, notFound = false }: IPropType) => {
  return (
    <>
      <Head>
        <title>{article.attributes.Slug} | My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 grid lg:grid-cols-3 gap-12">
        <div className="col-span-2">
          <h1 className="text-3xl font-bold py-2">
            {article.attributes.Title}
          </h1>
          <div className="flex items-center my-4">
            <div className="rounded-lg overflow-hidden flex items-center justify-center mr-2">
              <Image
                src={`http://localhost:1337${article.attributes.author.data.attributes.avatar.data.attributes.formats.thumbnail.url}`}
                height={40}
                width={40}
                alt="article-image"
              />
            </div>
            <span className="text-sm font-bold text-gray-600">
              {article.attributes.author.data.attributes.firstname}{" "}
              {article.attributes.author.data.attributes.lastname} on
              <span className="text-gray-400 ml-2">
                {dateFormat(article.attributes.createdAt)}
              </span>
            </span>
          </div>
          <div className="text-lg text-gray-600 leading-8">
            <img
              className="w-full my-12 mb-6"
              alt={article.attributes.Title}
              src={`http://localhost:1337${article.attributes.Image.data.attributes.url}`}
            />
            <MDXRemote
              {...(article.attributes.body as MDXRemoteSerializeResult)}
            />
            {/* {article.attributes.body} */}
          </div>
        </div>
        <div className="col-span-1">Right</div>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const queryString = qs.stringify({
    populate: ["Image", "author.avatar"],
    filters: {
      Slug: {
        $eq: query.slug,
      },
    },
  });
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticlBySlug(queryString);

  if (articles.data.length === 0) {
    return {
      props: {
        notFound: true,
      },
    };
  }
  return {
    props: {
      article: await serializedMarkDown(articles.data[0]),
    },
  };
};

export default Slug;
